export const GET_SWIPER_IMAGE_LIST_REQUEST = "GET_SWIPER_IMAGE_LIST_REQUEST";
export const GET_SWIPER_IMAGE_LIST_SUCCESS = "GET_SWIPER_IMAGE_LIST_SUCCESS";
export const GET_SWIPER_IMAGE_LIST_FAIL = "GET_SWIPER_IMAGE_LIST_FAIL";

export const GET_HOTCASE_LIST_REQUEST = "GET_HOTCASE_LIST_REQUEST";
export const GET_HOTCASE_LIST_SUCCESS = "GET_HOTCASE_LIST_SUCCESS";
export const GET_HOTCASE_LIST_FAIL = "GET_HOTCASE_LIST_FAIL";

export const GET_SPECIAL_ACTIVITY_LIST_REQUEST = "GET_SPECIAL_ACTIVITY_LIST_REQUEST";
export const GET_SPECIAL_ACTIVITY_LIST_SUCCESS = "GET_SPECIAL_ACTIVITY_LIST_SUCCESS";
export const GET_SPECIAL_ACTIVITY_LIST_FAIL = "GET_SPECIAL_ACTIVITY_LIST_FAIL";
