export const INIT_ORDER_REQUEST = "INIT_ORDER_REQUEST";
export const INIT_ORDER_PAY_LIST_REQUEST = "INIT_ORDER_PAY_LIST_REQUEST";

export const GET_ORDER_LIST_BY_USERID_REQUEST = "GET_ORDER_LIST_BY_USERID_REQUEST";
export const GET_ORDER_LIST_BY_USERID_SUCCESS = "GET_ORDER_LIST_BY_USERID_SUCCESS";
export const GET_ORDER_LIST_BY_USERID_FAIL = "GET_ORDER_LIST_BY_USERID_FAIL";

export const GET_ORDER_LIST_BY_USERID_AND_STATUS_REQUEST = "GET_ORDER_LIST_BY_USERID_AND_STATUS_REQUEST";
export const GET_ORDER_LIST_BY_USERID_AND_STATUS_SUCCESS = "GET_ORDER_LIST_BY_USERID_AND_STATUS_SUCCESS";
export const GET_ORDER_LIST_BY_USERID_AND_STATUS_FAIL = "GET_ORDER_LIST_BY_USERID_AND_STATUS_FAIL";

export const GET_ORDER_REQUEST = "GET_ORDER_REQUEST";
export const GET_ORDER_SUCCESS = "GET_ORDER_SUCCESS";
export const GET_ORDER_FAIL = "GET_ORDER_FAIL";

export const ADD_ORDER_LIST_REQUEST = "ADD_ORDER_LIST_REQUEST";
export const ADD_ORDER_LIST_SUCCESS = "ADD_ORDER_LIST_SUCCESS";
export const ADD_ORDER_LIST_FAIL = "ADD_ORDER_LIST_FAIL";

export const REMOVE_ORDER_REQUEST = "REMOVE_ORDER_REQUEST";
export const REMOVE_ORDER_SUCCESS = "REMOVE_ORDER_SUCCESS";
export const REMOVE_ORDER_FAIL = "REMOVE_ORDER_FAIL";

export const PAY_REQUEST = "PAY_REQUEST";
export const PAY_SUCCESS = "PAY_SUCCESS";
export const PAY_FAIL = "PAY_FAIL";

export const HAVE_RECEIVE_COMMODITY_REQUEST = "HAVE_RECEIVE_COMMODITY_REQUEST";
export const HAVE_RECEIVE_COMMODITY_SUCCESS = "HAVE_RECEIVE_COMMODITY_SUCCESS";
export const HAVE_RECEIVE_COMMODITY_FAIL = "HAVE_RECEIVE_COMMODITY_FAIL";

export const ADD_COMMENT_REQUEST = "ADD_COMMENT_REQUEST";
export const ADD_COMMENT_SUCCESS = "ADD_COMMENT_SUCCESS";
export const ADD_COMMENT_FAIL = "ADD_COMMENT_FAIL";


export const GET_COMMENT_LIST_REQUEST = "GET_COMMENT_LIST_REQUEST";
export const GET_COMMENT_LIST_SUCCESS = "GET_COMMENT_LIST_SUCCESS";
export const GET_COMMENT_LIST_FAIL = "GET_COMMENT_LIST_FAIL";