//商店设置
export const GET_SHOP_REQUEST = 'GET_SHOP_REQUEST';
export const GET_SHOP_SUCCESS = 'GET_SHOP_SUCCESS';
export const GET_SHOP_FAIL = 'GET_SHOP_FAIL';


export const GET_COMMODITY_CATE_LIST_REQUEST = 'GET_COMMODITY_CATE_LIST_REQUEST';
export const GET_COMMODITY_CATE_LIST_SUCCESS = 'GET_COMMODITY_CATE_LIST_SUCCESS';
export const GET_COMMODITY_CATE_LIST_FAIL = 'GET_COMMODITY_CATE_LIST_FAIL';

