export const CHANGE_PHONE_NUMBER = 'CHANGE_PHONE_NUMBER';
// 注册
export const LOGIN_UP_REQUEST = 'LOGIN_UP_REQUEST';
export const LOGIN_UP_SUCCESS = 'LOGIN_UP_SUCCESS';
export const LOGIN_UP_FAIL = 'LOGIN_UP_FAIL';

export const LOGIN_IN_REQUEST = 'LOGIN_IN_REQUEST';
export const LOGIN_IN_SUCCESS = 'LOGIN_IN_SUCCESS';
export const LOGIN_IN_FAIL = 'LOGIN_IN_FAIL';

export const LOGIN_OUT_REQUEST = 'LOGIN_OUT_REQUEST';
export const LOGIN_OUT_SUCCESS = 'LOGIN_OUT_SUCCESS';
export const LOGIN_OUT_FAIL = 'LOGIN_OUT_FAIL';
//用户基本信息
export const GET_USER_REQUEST = 'GET_USER_REQUEST';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAIL = 'GET_USER_FAIL';

export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAIL = 'UPDATE_USER_FAIL';

//收藏
export const ADD_COLLECTION_REQUEST = 'ADD_COLLECTION_REQUEST';
export const ADD_COLLECTION_SUCCESS = 'ADD_COLLECTION_SUCCESS';
export const ADD_COLLECTION_FAIL = 'ADD_COLLECTION_FAIL';

export const GET_COLLECTION_LIST_REQUEST = 'GET_COLLECTION_LIST_REQUEST';
export const GET_COLLECTION_LIST_SUCCESS = 'GET_COLLECTION_LIST_SUCCESS';
export const GET_COLLECTION_LIST_FAIL = 'GET_COLLECTION_LIST_FAIL';

export const REMOVE_COLLECTION_REQUEST = 'REMOVE_COLLECTION_REQUEST';
export const REMOVE_COLLECTION_SUCCESS = 'REMOVE_COLLECTION_SUCCESS';
export const REMOVE_COLLECTION_FAIL = 'REMOVE_COLLECTION_FAIL';

//地址
export const ADD_ADDRESS_REQUEST = 'ADD_ADDRESS_REQUEST';
export const ADD_ADDRESS_SUCCESS = 'ADD_ADDRESS_SUCCESS';
export const ADD_ADDRESS_FAIL = 'ADD_ADDRESS_FAIL';

export const GET_ADDRESS_LIST_REQUEST = 'GET_ADDRESS_LIST_REQUEST';
export const GET_ADDRESS_LIST_SUCCESS = 'GET_ADDRESS_LIST_SUCCESS';
export const GET_ADDRESS_LIST_FAIL = 'GET_ADDRESS_LIST_FAIL';

export const UPDATE_ADDRESS_REQUEST = 'UPDATE_ADDRESS_REQUEST';
export const UPDATE_ADDRESS_SUCCESS = 'UPDATE_ADDRESS_SUCCESS';
export const UPDATE_ADDRESS_FAIL = 'UPDATE_ADDRESS_FAIL';

export const REMOVE_ADDRESS_REQUEST = 'REMOVE_ADDRESS_REQUEST';
export const REMOVE_ADDRESS_SUCCESS = 'REMOVE_ADDRESS_SUCCESS';
export const REMOVE_ADDRESS_FAIL = 'REMOVE_ADDRESS_FAIL';

//购物车
export const ADD_COMMODITY_TO_SHOP_CAR_REQUEST = 'ADD_COMMODITY_TO_SHOP_CAR_REQUEST';
export const ADD_COMMODITY_TO_SHOP_CAR_SUCCESS = 'ADD_COMMODITY_TO_SHOP_CAR_SUCCESS';
export const ADD_COMMODITY_TO_SHOP_CAR_FAIL = 'ADD_COMMODITY_TO_SHOP_CAR_FAIL';

export const GET_SHOP_CAR_COMMODITY_LIST_REQUEST = 'GET_SHOP_CAR_COMMODITY_LIST_REQUEST';
export const GET_SHOP_CAR_COMMODITY_LIST_SUCCESS = 'GET_SHOP_CAR_COMMODITY_LIST_SUCCESS';
export const GET_SHOP_CAR_COMMODITY_LIST_FAIL = 'GET_SHOP_CAR_COMMODITY_LIST_FAIL';

export const REMOVE_COMMODITY_FROM_SHOP_CAR_REQUEST = 'REMOVE_COMMODITY_FROM_SHOP_CAR_REQUEST';
export const REMOVE_COMMODITY_FROM_SHOP_CAR_SUCCESS = 'REMOVE_COMMODITY_FROM_SHOP_CAR_SUCCESS';
export const REMOVE_COMMODITY_FROM_SHOP_CAR_FAIL = 'REMOVE_COMMODITY_FROM_SHOP_CAR_FAIL';

export const REMOVE_COMMODITY_LIST_FROM_SHOP_CAR_REQUEST = 'REMOVE_COMMODITY_LIST_FROM_SHOP_CAR_REQUEST';
export const REMOVE_COMMODITY_LIST_FROM_SHOP_CAR_SUCCESS = 'REMOVE_COMMODITY_LIST_FROM_SHOP_CAR_SUCCESS';
export const REMOVE_COMMODITY_LIST_FROM_SHOP_CAR_FAIL = 'REMOVE_COMMODITY_LIST_FROM_SHOP_CAR_FAIL';


